project:
  type: book
  output-dir: docs

book:
  title: "재무회계 목적의 가치평가 with R (Financial Accounting Valuation with R)"
  author: "형환희, 이광춘"
  date: "2024. 4. 15."
  chapters:
    - index.qmd
    - intro.qmd
    - fairvalue.qmd
    - data.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo햣
  pdf:
    documentclass: scrreprt



