---
output: html_document
editor_options: 
  chunk_output_type: console
---
# 공정가치의 정의
  
## 재무회계 공정가치의 정의

한국채택국제회계기준(이하 '기준서')은 공정가치로 측정 평가하는 방법을 지향합니다. 공정가치라는 표현은 경우에 따라서 다른 의미가 될 수도 있으므로 재무회계에서 다루는 공정가치의 정의를 명확하게 할 필요가 있습니다.    
   
* 기준서 제1113호 - 공정가치 측정  
  
### 목적

> 1113.2 공정가치는 시장에 근거한 측정치이며 기업 특유의 측정치가 아니다. 일부 자산과 부채의 경우에는 관측할 수 있는 시장 거래나 시장 정보를 구할 수 있다. 다른 자산과 부채의 경우에는 관측할 수 있는 시장 거래와 시장 정보를 구하지 못할 수 있다. 그러나 두 경우 모두 공정가치를 측정하는 목적은 측정일 현재의 시장 상황에서 시장참여자 사이에 자산을 매도하거나 부채를 이전하는 정상거래가 있는 경우의 가격(자산을 보유하거나 부채를 부담하는 시장참여자의 관점에서 측정일의 유출가격)을 추정하는 것이라는 점에서 같다.
  
> 1113.3 동일한 자산이나 부채의 가격을 관측할 수 없는 경우에는 관측할 수 있는 관련된투입변수를 최대한으로 사용하고 관측할 수 없는 투입변수를 최소한으로 사용하는 다른 가치평가기법을 사용하여 공정가치를 측정한다. 공정가치는 시장에 근거한 측정치이므로 위험에 대한 가정을 포함하여, 시장참여자가 자산이나 부채의 가격을 결정할 때 사용하게 될 가정을 사용하여 측정된다. 결과적으로 기업이 자산을 보유하려는 의도는 부채를 결제하거나 이행하려는 공정가치를 측정할 때 관련이 없다.
   
> 1113.4 공정가치의 정의는 자산과 부채에 초점을 두는데 이는 자산과 부채가 회계에서 측정의 주요 대상이기 때문이다. 또한 이 기준서는 공정가치로 측정하는 자기지분상품에도 적용된다.
  
### 공정가치의 정의
  
> 1113.9 이 기준서에서는 공정가치를 측정일에 시장참여자 사이의 정상거래에서 자산을 매도할 때 받거나 부채를 이전할 때 지급하게 될 가격으로 정의한다.    
   
   
기준서 상 공정가치의 정의는 특수관계자(한국채택국제회계기준 제1024호)가 아닌 서로 독립적인 시장참여자가 합리적인 판단력 하에서 통상적이고 관습적인 시장에 노출되는 상태의 정상거래(주된 시장 - 자산이나 부채의 주된 시장이 없는 경우에는 가장 유리한 시장)^[주된 시장은 해당 항목에 대한 거래의 규모나 빈도가 가장 큰 시장을 말하며 가장 유리한 시장은 거래원가나 운송원가를 고려했을 때 자산을 매도하면서 수취하는 금액을 최대화 하거나 부채를 이전하면서 지급하는 금액을 최소화 하는 시장입니다.]에서 자산의 매도 또는 부채의 이전에 있어 지급하게 될 가격입니다.  
  
이를 회계처리에 적용하는 분개로 표현하면 다음과 같습니다.  
  
* 자산을 매도할 때  

차변 | 대변 |
-----|------|
현금(공정가치) | 자산 | 


* 부채를 이전할 때

차변 | 대변 |
-----|------|
부채 | 현금(공정가치) | 
  

### 가격의 의미
  
일반적으로 생각하는 공정가치 가격은 시장에서 관측한 값을 의미합니다. 상장회사 주식의 경우 시장이 열리는 시간(영업일의 9시부터 3시 30분까지)에 거래되는 가격을 공정가치 가격으로 생각하면 쉽습니다. 시간 외 거래도 일어날 수는 있으나 3시 30분에 결정되어 마감된 가격을 종가라고 부르며 이 활성시장의 종가를 그 날의 공정가치로 적용하는 경우가 많습니다.  
  
그러나 상장회사의 주식과 같이 활성시장의 거래 가격이 존재하지 않는 경우에는 시장에 근거한 측정치 등을 활용하여 적절한 가치를 계산해야 할 수도 있습니다. 본 서의 공정가치평가는 이러한 경우를 염두에 두었습니다.    
    
> 1113.2 공정가치는 시장에 근거한 측정치이며 기업 특유의 측정치가 아니다. 일부 자산과 부채의 경우에는 관측할 수 있는 시장 거래나 시장 정보를 구할 수 있다. 다른 자산과 부채의 경우에는 관측할 수 있는 시장 거래와 시장 정보를 구하지 못할 수 있다. 그러나 두 경우 모두 공정가치를 측정하는 목적은 측정일 현재의 시장 상황에서 시장참여자 사이에 자산을 매도하거나 부채를 이전하는 정상거래가 있는 경우의 가격(자산을 보유하거나 부채를 부담하는 시장참여자의 관점에서 측정일의 유출가격)을 추정하는 것이라는 점에서 같다.
  
